[package]
name = "dump"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#lower = { path = "../lower" }
flat = { path = "../flat" }
compile_core = { path = "../compile_core" }
tabled = "0.15.0"
serde = "1.0"
serde_json = "*"
petgraph = "0.6.4"



